import sys
import os

# Add the project root to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')  # Adjust if needed
django.setup()

from django.db import connection
from django.test.utils import CaptureQueriesContext
from django.test import RequestFactory

def capture_orm_queries(view_functions, output_file):
    """
    Captures SQL queries generated by ORM calls in specified view functions.

    :param view_functions: List of view functions to execute.
    :param output_file: Path to save the captured SQL queries.
    """
    sql_queries = []
    factory = RequestFactory()

    for view_func in view_functions:
        # Create a mock GET request
        request = factory.get("/")  # Adjust the path if needed
        with CaptureQueriesContext(connection) as queries:
            try:
                # Call the view function with the mock request
                response = view_func(request)
                print(f"Response status: {response.status_code}")  # Optional: log the response
            except Exception as e:
                print(f"Error executing view {view_func.__name__}: {e}")

            # Add executed queries to the list
            for query in queries.captured_queries:
                sql_queries.append(query['sql'])

    # Write SQL queries to output file
    with open(output_file, 'w', encoding='utf-8') as sql_file:
        sql_file.write("-- Captured ORM SQL Queries\n\n")
        for query in sql_queries:
            sql_file.write(query + ";\n")

    print(f"Captured {len(sql_queries)} SQL queries.")

# Example usage
if __name__ == "__main__":
    # Import your views here
    from app.views import get_candidates_testReports
  # Adjust imports

    # List the view functions to test
    view_functions_to_test = [get_candidates_testReports
]

    # Absolute file path to save SQL
    output_sql_file = os.path.join(os.path.dirname(__file__), '../output.sql')

    # Capture queries
    capture_orm_queries(view_functions_to_test, output_sql_file)
