# Generated by Django 5.0.3 on 2026-03-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_paper_master_folder_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_master',
            name='temp1',
        ),
        migrations.AddField(
            model_name='test_master',
            name='score_display',
            field=models.BooleanField(default=False),
        ),
    ]
